spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/camunda_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  cloud:
    openfeign:
      client:
        config:
          workflows:
            url: ${WORKFLOW_SERVICE_URL:http://localhost:8090}
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
camunda:
  bpm:
    admin-user:
      id: ${ADMIN_USER:demo}
      password: ${ADMIN_PASSWORD:demo}
    database:
      type: mysql
    history-level: full
